import { describe, expect, test } from "bun:test";
import { generateImageTool } from "./image";
import { StateFilesConsentError, type StateFilesAssetWriter } from "./state-files";

type Tool = ReturnType<typeof generateImageTool>;
type ExecuteInput = Parameters<Tool["execute"]>[0];

function imageResult() {
  return {
    image: {
      mediaType: "image/png",
      uint8Array: new Uint8Array([1, 2, 3, 4]),
    },
    warnings: ["soft warning"],
  };
}

function recordingWriter(): StateFilesAssetWriter & {
  readonly writes: { path: string; body: Uint8Array; contentType?: string }[];
} {
  const writes: { path: string; body: Uint8Array; contentType?: string }[] = [];
  return {
    writes,
    async write(path, body, options) {
      writes.push({ path, body, ...(options?.contentType === undefined ? {} : { contentType: options.contentType }) });
    },
  };
}

describe("generateImageTool", () => {
  test("writes generated bytes through state files and emits a stable state_asset reference", async () => {
    const writer = recordingWriter();
    const tool = generateImageTool({
      assetWriter: writer,
      declarationName: "files",
      randomId: () => "abc12345",
      generate: async () => imageResult(),
    });

    const output = await tool.execute(
      { prompt: "Blue robot", outputDir: "generated" } satisfies ExecuteInput,
      new Proxy({}, {
        get(_, property) {
          if (property === "getSandbox") {
            throw new Error("generate_image must not write generated assets through ctx.getSandbox()");
          }
          return undefined;
        },
      }) as Parameters<Tool["execute"]>[1],
    );

    expect(writer.writes).toEqual([
      {
        path: "generated/blue-robot-abc12345.png",
        body: new Uint8Array([1, 2, 3, 4]),
        contentType: "image/png",
      },
    ]);
    expect(output.asset).toEqual({
      type: "state_asset",
      declarationName: "files",
      path: "generated/blue-robot-abc12345.png",
      contentType: "image/png",
      bytes: 4,
    });
    expect(JSON.stringify(output)).not.toContain("credential");
    expect(JSON.stringify(output)).not.toContain("http");
    expect(JSON.stringify(output)).not.toContain("handle");
  });

  test("toModelOutput names the state asset without inventing a URL", async () => {
    const tool = generateImageTool({
      assetWriter: recordingWriter(),
      generate: async () => imageResult(),
    });

    const modelOutput = await tool.toModelOutput?.({
      asset: {
        type: "state_asset",
        declarationName: "files",
        path: "generated/cat-abc12345.png",
        contentType: "image/png",
        bytes: 4,
      },
      bytes: 4,
      mediaType: "image/png",
      model: "bfl/flux-2-pro",
      path: "generated/cat-abc12345.png",
      prompt: "cat",
      warnings: [],
    });

    expect(modelOutput).toEqual({
      type: "text",
      // bun-types' `AsymmetricMatcher` is a bare `any`; narrow it to the real
      // field type so this assignment stays type-checked.
      value: expect.stringContaining("files:generated/cat-abc12345.png") as string,
    });
    expect(JSON.stringify(modelOutput)).toContain("state_asset");
    expect(JSON.stringify(modelOutput)).not.toContain("http");
    expect(JSON.stringify(modelOutput)).not.toContain("workspace images yet");
  });

  test("surfaces a state-files consent steer instead of swallowing it (bead zo-oxg.27.10)", async () => {
    // The writer's `consent_required` gate must propagate through execute so eve
    // renders the steer as the tool-error the model reacts to — the tool never
    // catches or transforms it into a fake success.
    const envelope = {
      bindingId: "stb_abc123",
      declarationName: "files",
      resourceName: "Files",
      party: { handle: "org_acme", external: false } as const,
    };
    const consentWriter: StateFilesAssetWriter = {
      async write() {
        throw new StateFilesConsentError(envelope);
      },
    };
    const tool = generateImageTool({
      assetWriter: consentWriter,
      declarationName: "files",
      randomId: () => "abc12345",
      generate: async () => imageResult(),
    });

    let error: unknown = null;
    try {
      await tool.execute(
        { prompt: "Blue robot", outputDir: "generated" } satisfies ExecuteInput,
        new Proxy({}, {}) as Parameters<Tool["execute"]>[1],
      );
    } catch (caught) {
      error = caught;
    }
    expect(error).toBeInstanceOf(StateFilesConsentError);
    if (error instanceof StateFilesConsentError) {
      expect(error.envelope).toEqual(envelope);
      expect(error.message).toContain("request_state_consent");
    }
  });
});
