import { describe, expect, test } from "bun:test";
import { generateImageTool } from "./image";
import type { StateFilesAssetWriter } from "./state-files";

type Tool = ReturnType<typeof generateImageTool>;
type ExecuteInput = Parameters<Tool["execute"]>[0];

function imageResult() {
  return {
    image: {
      mediaType: "image/png",
      uint8Array: new Uint8Array([1, 2, 3, 4]),
    },
    warnings: ["soft warning"],
  };
}

function recordingWriter(): StateFilesAssetWriter & {
  readonly writes: { path: string; body: Uint8Array; contentType?: string }[];
} {
  const writes: { path: string; body: Uint8Array; contentType?: string }[] = [];
  return {
    writes,
    async write(path, body, options) {
      writes.push({ path, body, ...(options?.contentType === undefined ? {} : { contentType: options.contentType }) });
    },
  };
}

describe("generateImageTool", () => {
  test("writes generated bytes through state files and emits a stable state_asset reference", async () => {
    const writer = recordingWriter();
    const tool = generateImageTool({
      assetWriter: writer,
      declarationName: "files",
      randomId: () => "abc12345",
      generate: async () => imageResult(),
    });

    const output = await tool.execute(
      { prompt: "Blue robot", outputDir: "generated" } satisfies ExecuteInput,
      new Proxy({}, {
        get(_, property) {
          if (property === "getSandbox") {
            throw new Error("generate_image must not write generated assets through ctx.getSandbox()");
          }
          return undefined;
        },
      }) as Parameters<Tool["execute"]>[1],
    );

    expect(writer.writes).toEqual([
      {
        path: "generated/blue-robot-abc12345.png",
        body: new Uint8Array([1, 2, 3, 4]),
        contentType: "image/png",
      },
    ]);
    expect(output.asset).toEqual({
      type: "state_asset",
      declarationName: "files",
      path: "generated/blue-robot-abc12345.png",
      contentType: "image/png",
      bytes: 4,
    });
    expect(JSON.stringify(output)).not.toContain("credential");
    expect(JSON.stringify(output)).not.toContain("http");
    expect(JSON.stringify(output)).not.toContain("handle");
  });

  test("toModelOutput names the state asset without inventing a URL", async () => {
    const tool = generateImageTool({
      assetWriter: recordingWriter(),
      generate: async () => imageResult(),
    });

    const modelOutput = await tool.toModelOutput?.({
      asset: {
        type: "state_asset",
        declarationName: "files",
        path: "generated/cat-abc12345.png",
        contentType: "image/png",
        bytes: 4,
      },
      bytes: 4,
      mediaType: "image/png",
      model: "bfl/flux-2-pro",
      path: "generated/cat-abc12345.png",
      prompt: "cat",
      warnings: [],
    });

    expect(modelOutput).toEqual({
      type: "text",
      value: expect.stringContaining("files:generated/cat-abc12345.png"),
    });
    expect(JSON.stringify(modelOutput)).toContain("state_asset");
    expect(JSON.stringify(modelOutput)).not.toContain("http");
    expect(JSON.stringify(modelOutput)).not.toContain("workspace images yet");
  });
});
