import { describe, expect, test } from "bun:test";
import { generateVideoTool } from "./video";
import type { StateFilesAssetWriter } from "./state-files";

type Tool = ReturnType<typeof generateVideoTool>;
type ExecuteInput = Parameters<Tool["execute"]>[0];
// The executor never touches ctx; a bare stub typed as the ctx parameter suffices.
// A Proxy (not an object literal) keeps `consistent-type-assertions` happy.
const toolContext = new Proxy({}, {}) as Parameters<Tool["execute"]>[1];

function videoResult() {
  return {
    video: {
      mediaType: "video/mp4",
      uint8Array: new Uint8Array([9, 8, 7, 6, 5]),
    },
    warnings: ["soft warning"],
  };
}

function recordingWriter(): StateFilesAssetWriter & {
  readonly writes: { path: string; body: Uint8Array; contentType?: string }[];
} {
  const writes: { path: string; body: Uint8Array; contentType?: string }[] = [];
  return {
    writes,
    async write(path, body, options) {
      writes.push({ path, body, ...(options?.contentType === undefined ? {} : { contentType: options.contentType }) });
    },
  };
}

describe("generateVideoTool", () => {
  test("writes generated bytes through state files and emits a stable state_asset reference", async () => {
    const writer = recordingWriter();
    const captured: unknown[] = [];
    const tool = generateVideoTool({
      assetWriter: writer,
      declarationName: "files",
      randomId: () => "vid99999",
      generate: async (options) => {
        captured.push(options);
        return videoResult();
      },
    });

    const output = await tool.execute(
      { prompt: "A calico cat", aspect_ratio: "16:9", duration_seconds: 5 } satisfies ExecuteInput,
      toolContext,
    );

    expect(writer.writes).toEqual([
      {
        path: "generated/a-calico-cat-vid99999.mp4",
        body: new Uint8Array([9, 8, 7, 6, 5]),
        contentType: "video/mp4",
      },
    ]);
    expect(output.asset).toEqual({
      type: "state_asset",
      declarationName: "files",
      path: "generated/a-calico-cat-vid99999.mp4",
      contentType: "video/mp4",
      bytes: 5,
    });
    // Optional inputs pass through to the generation call.
    expect(captured[0]).toMatchObject({ aspectRatio: "16:9", duration: 5, prompt: "A calico cat" });
    expect(JSON.stringify(output)).not.toContain("credential");
    expect(JSON.stringify(output)).not.toContain("http");
    expect(JSON.stringify(output)).not.toContain("handle");
  });

  test("omits unset optional inputs from the generation call", async () => {
    const captured: unknown[] = [];
    const tool = generateVideoTool({
      assetWriter: recordingWriter(),
      randomId: () => "vid00001",
      generate: async (options) => {
        captured.push(options);
        return videoResult();
      },
    });

    await tool.execute({ prompt: "waves" } satisfies ExecuteInput, toolContext);

    expect(captured[0]).not.toHaveProperty("aspectRatio");
    expect(captured[0]).not.toHaveProperty("duration");
    expect(captured[0]).not.toHaveProperty("seed");
  });

  test("maps a failed generation call to model-actionable feedback", async () => {
    const tool = generateVideoTool({
      assetWriter: recordingWriter(),
      generate: async () => {
        throw new Error("rate limited (429)");
      },
    });

    const attempt = tool.execute({ prompt: "waves" } satisfies ExecuteInput, toolContext);

    await expect(attempt).rejects.toThrow("No video was generated");
    await expect(attempt).rejects.toThrow("rate limited (429)");
  });

  test("maps a failed asset write to model-actionable feedback", async () => {
    const failingWriter: StateFilesAssetWriter = {
      async write() {
        throw new Error("the storage write was rejected with HTTP 500");
      },
    };
    const tool = generateVideoTool({
      assetWriter: failingWriter,
      generate: async () => videoResult(),
    });

    const attempt = tool.execute({ prompt: "waves" } satisfies ExecuteInput, toolContext);

    await expect(attempt).rejects.toThrow("no state asset was saved");
    await expect(attempt).rejects.toThrow("HTTP 500");
  });

  test("toModelOutput names the state asset without inventing a URL", async () => {
    const tool = generateVideoTool({
      assetWriter: recordingWriter(),
      generate: async () => videoResult(),
    });

    const modelOutput = await tool.toModelOutput?.({
      asset: {
        type: "state_asset",
        declarationName: "files",
        path: "generated/cat-vid99999.mp4",
        contentType: "video/mp4",
        bytes: 5,
      },
      bytes: 5,
      mediaType: "video/mp4",
      model: "bytedance/seedance-2.0-fast",
      path: "generated/cat-vid99999.mp4",
      prompt: "cat",
      warnings: [],
    });

    expect(modelOutput?.type).toBe("text");
    expect(JSON.stringify(modelOutput)).toContain("files:generated/cat-vid99999.mp4");
    expect(JSON.stringify(modelOutput)).toContain("state_asset");
    expect(JSON.stringify(modelOutput)).not.toContain("http");
  });
});
